In [3]:
import netCDF4 as nc

In [4]:
fn = '/Users/shiyangxu/Downloads/byan/wavm-inner_wave.nc'

In [5]:
ds = nc.Dataset(fn)

In [6]:
print(ds)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    institution: Deltares
    references: http://www.deltares.nl
    source: Deltares, Delft3D-WAVE Version 3.07.00.62434, Oct 24 2018, 14:38:32
    history: Created on 2023-04-25T11:35:22+0800, Delft3D-WAVE
    dimensions(sizes): mmax(287), nmax(210), time(4)
    variables(dimensions): int32 projected_coordinate_system(), float64 x(nmax, mmax), float64 y(nmax, mmax), float64 time(time), int32 kcs(nmax, mmax), float64 hsign(time, nmax, mmax), float64 dir(time, nmax, mmax), float64 pdir(time, nmax, mmax), float64 period(time, nmax, mmax), float64 rtp(time, nmax, mmax), float64 depth(time, nmax, mmax), float64 veloc-x(time, nmax, mmax), float64 veloc-y(time, nmax, mmax), float64 transp-x(time, nmax, mmax), float64 transp-y(time, nmax, mmax), float64 dspr(time, nmax, mmax), float64 dissip(time, nmax, mmax), float64 leak(time, nmax, mmax), float64 qb(time, nmax, mmax), float64 ubot(time, nmax, 

In [7]:
print(ds.__dict__)

{'institution': 'Deltares', 'references': 'http://www.deltares.nl', 'source': 'Deltares, Delft3D-WAVE Version 3.07.00.62434, Oct 24 2018, 14:38:32', 'history': 'Created on 2023-04-25T11:35:22+0800, Delft3D-WAVE'}


In [8]:
print(ds.__dict__['institution'])

Deltares


In [9]:
print(ds.dimensions)

{'mmax': <class 'netCDF4._netCDF4.Dimension'>: name = 'mmax', size = 287, 'nmax': <class 'netCDF4._netCDF4.Dimension'>: name = 'nmax', size = 210, 'time': <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'time', size = 4}


In [10]:
for var in ds.variables.values():
    print(var)

<class 'netCDF4._netCDF4.Variable'>
int32 projected_coordinate_system()
    name: WGS84
    grid_mapping_name: latitude_longitude
    epsg: 4326
    longitude_of_prime_meridian: 0.0
    semi_major_axis: 6378137.0
    semi_minor_axis: 6356752.314245
    inverse_flattening: 298.257223563
    proj4_params: 
    EPSG_code: EPGS:4326
    projection_name: 
    wkt: 
    comment: 
    value: value is equal to EPSG code
unlimited dimensions: 
current shape = ()
filling on, default _FillValue of -2147483647 used
<class 'netCDF4._netCDF4.Variable'>
float64 x(nmax, mmax)
    standard_name: projection_x_coordinate
    long_name: x-coordinate of cell centres
    units: deg
    grid_mapping: projected_coordinate_system
unlimited dimensions: 
current shape = (210, 287)
filling on, default _FillValue of 9.969209968386869e+36 used
<class 'netCDF4._netCDF4.Variable'>
float64 y(nmax, mmax)
    standard_name: projection_y_coordinate
    long_name: y-coordinate of cell centres
    units: deg
    grid_mappi

In [12]:
print(ds['x'][:].shape)

(210, 287)


print(ds)

In [13]:
print(ds['y'][:].shape)

(210, 287)


In [30]:
print(ds['y'][:,0])

[22.1778 22.1782 22.1786 22.179  22.1794 22.1798 22.1802 22.1806 22.181
 22.1814 22.1818 22.1822 22.1826 22.183  22.1834 22.1838 22.1842 22.1846
 22.185  22.1854 22.1858 22.1862 22.1866 22.187  22.1874 22.1878 22.1882
 22.1886 22.189  22.1894 22.1898 22.1902 22.1906 22.191  22.1914 22.1918
 22.1922 22.1926 22.193  22.1934 22.1938 22.1942 22.1946 22.195  22.1954
 22.1958 22.1962 22.1966 22.197  22.1974 22.1978 22.1982 22.1986 22.199
 22.1994 22.1998 22.2002 22.2006 22.201  22.2014 22.2018 22.2022 22.2026
 22.203  22.2034 22.2038 22.2042 22.2046 22.205  22.2054 22.2058 22.2062
 22.2066 22.207  22.2074 22.2078 22.2082 22.2086 22.209  22.2094 22.2098
 22.2102 22.2106 22.211  22.2114 22.2118 22.2122 22.2126 22.213  22.2134
 22.2138 22.2142 22.2146 22.215  22.2154 22.2158 22.2162 22.2166 22.217
 22.2174 22.2178 22.2182 22.2186 22.219  22.2194 22.2198 22.2202 22.2206
 22.221  22.2214 22.2218 22.2222 22.2226 22.223  22.2234 22.2238 22.2242
 22.2246 22.225  22.2254 22.2258 22.2262 22.2266 22.22

In [2]:
import matlab.engine
import numpy as np
import netCDF4 as nc
import math
import time

def avg(val, data_type):
    if (data_type == 0):
        sum = 0
        len = 0
        for v in val:
            if v != -1:
                sum += v
                len += 1
        sum /= len
        return sum
    
    elif (data_type == 1):
        xsum = 0
        ysum = 0
        len = 0

        for v in val:
            xsum += math.sin(np.deg2rad(v))
            ysum += math.cos(np.deg2rad(v))
            len += 1
        xsum /= len
        ysum /= len
        avg_deg = np.rad2deg(math.atan2(ysum, xsum))

        return avg_deg

def zoom(arr, mult, data_type):
    arr_shape = np.shape(arr)
    arr_mod_shape = [math.ceil(s/mult) for s in arr_shape]

    arr_mod = np.zeros(arr_mod_shape)

    for i in range(arr_mod_shape[0]):
        for j in range(arr_mod_shape[1]):
            val_list = []    

            for x in range(mult):
                if (i*mult+x < arr_shape[0]):
                    for y in range(mult):
                        if (j*mult+y < arr_shape[1]):
                            val_list.append(arr[i*mult+x][j*mult+y])

            arr_mod[i][j] = avg(val_list, data_type)   
    
    return arr_mod


# arr = np.array([[1,3,4,9],
#        [8,4,6,2],
#        [7,3,2,1],
#        [2,7,3,0] 
# ])

# arr_mod = zoom(arr, 4)

eng = matlab.engine.start_matlab()

path = "/Users/shiyangxu/Downloads/byan/wavm-inner_wave.nc"
data = nc.Dataset(path)

x = np.array(data['x'])
y = np.array(data['y'])
depth = np.array(data['depth'][0, :, :])
param = np.array(data['hsign'][0, :, :])

# arr_shape = np.shape(x)
# for i in range(arr_shape[0]):
#     for j in range(arr_shape[1]):
#         if (depth[i][j] == 0.):
#             param[i][j] = -1

fac = 8 
x_mod = zoom(x, fac, 0)
y_mod = zoom(y, fac, 0)
param_mod = zoom(param, fac, 0)

eng.pcolor(x_mod, y_mod, param_mod)

t = time.time()
while (time.time()-t) < 20:
    a = 1
eng.quit()

In [19]:
import numpy as np

X = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print (X[0,:,:])

[[1 2]
 [3 4]]


In [21]:
x = np.array([[[23.64999962, 23.76000023, 23.80999947, 34.22999954, 34.13999939, 34.18000031],
  [23.71999931, 23.81999969, 23.81999969, 34.20000076, 34.18999863, 34.24000168],
  [23.79000092, 23.73999977, 23.78000069, 34.20000076, 34.22999954, 34.27000046]], 
  [[23.64999962, 23.76000023, 23.80999947, 34.22999954, 34.13999939, 34.18000031],
  [23.71999931, 23.81999969, 23.81999969, 34.20000076, 34.18999863, 34.24000168],
   [23.79000092, 23.73999977, 23.78000069, 34.20000076, 34.22999954, 34.27000046]]])

In [22]:
print(x[0,:,:])

[[23.64999962 23.76000023 23.80999947 34.22999954 34.13999939 34.18000031]
 [23.71999931 23.81999969 23.81999969 34.20000076 34.18999863 34.24000168]
 [23.79000092 23.73999977 23.78000069 34.20000076 34.22999954 34.27000046]]


In [17]:
print(x.shape)

(210, 287)


In [18]:
print(y.shape)

(210, 287)


In [22]:
import numpy as np
import netCDF4 as nc
from json import JSONEncoder
import json
import math

## Definition of numpy array encoder class for serialization of ndnumpy array into json string ##
class NumpyArrayEncoder(JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return JSONEncoder.default(self, obj)
## ------------------------------------------------------------------------------------------- ##

## Extraction of wave data parameters from .nc file ##
path = "/Users/shiyangxu/Downloads/byan/wavm-inner_wave.nc"
data = nc.Dataset(path)
json_filename = "Data.json"

x = np.array(data['x'])
y = np.array(data['y'])
depth = np.array(data['depth'][0, :, :])
wave_ht = np.array(data['hsign'][0, :, :])
wave_dir = np.array(data['dir'][0, :, :])
## ------------------------------------------------ ##

## Customizable user settings for rasterizing wave data ##
fac = 1
## ---------------------------------------------------- ##

## Definition of functions ##
def avg(val, data_type):  
    # data_type - 0: x,y; 1: direction, 2: others
    if (data_type == 1):
        xsum = 0
        ysum = 0
        len = 0

        for v in val:
            # if v != -1.:
            xsum += math.sin(np.deg2rad(v))
            ysum += math.cos(np.deg2rad(v))
            len += 1

        if (len > 0):
            xsum /= len
            ysum /= len
            
        avg_deg = np.rad2deg(math.atan2(ysum, xsum))
        return avg_deg
    
    else:
        sum = 0
        len = 0
        for v in val:
            # if v != -1.:
            sum += v
            len += 1
        if (len > 0):
            sum /= len
        return sum

def zoom(arr, mult, data_type):
    # data_type - 0: x,y; 1: direction, 2: others
    arr_shape = np.shape(arr)
    arr_mod_shape = [math.ceil(s/mult) for s in arr_shape]

    arr_mod = np.zeros(arr_mod_shape)
    for i in range(arr_mod_shape[0]):
        for j in range(arr_mod_shape[1]):
            val_list = []    
            for x in range(mult):
                if (i*mult+x < arr_shape[0]):
                    for y in range(mult):
                        if (j*mult+y < arr_shape[1]):
                            val_list.append(arr[i*mult+x][j*mult+y])
            arr_mod[i][j] = avg(val_list, data_type)   

    return arr_mod
## ----------------------- ##

## Modification of data according to a multiplication factor ##
x_mod = zoom(x, fac, 0)
y_mod = zoom(y, fac, 0)
wave_ht_mod = zoom(wave_ht, fac, 2)
wave_dir_mod = zoom(wave_dir, fac, 1)
## --------------------------------------------------------- ##

## Publishing of wave data into JSON file ##
wave_data = {"X": x, "Y": y, "waveHeight": wave_ht_mod, "waveDirection": wave_dir_mod}
print(f"Serializing wave data into JSON string and writing into {json_filename}")
with open(json_filename, "w") as write_file:
    json.dump(wave_data, write_file, cls=NumpyArrayEncoder)
print(f"Done writing serialized wave data into {json_filename}")
## -------------------------------------- ##

## Extraction of wave data from JSON file as test ##
print("Started Reading JSON file")
with open(json_filename, "r") as read_file:
    print("Converting JSON encoded data into Numpy array")
    decodedArray = json.load(read_file)
    print("X")
    print(x)
    print("Y")
    print(y)
    finalNumpyArrayOne = np.asarray(decodedArray["waveHeight"])
    print("Wave height")
    print(finalNumpyArrayOne)
    finalNumpyArrayTwo = np.asarray(decodedArray["waveDirection"])
    print("Wave direction")
    print(finalNumpyArrayTwo)
## ----------------------------------------------- ##

Serializing wave data into JSON string and writing into Data.json
Done writing serialized wave data into Data.json
Started Reading JSON file
Converting JSON encoded data into Numpy array
X
[[114.19   114.1904 114.1908 ... 114.3036 114.304  114.3044]
 [114.19   114.1904 114.1908 ... 114.3036 114.304  114.3044]
 [114.19   114.1904 114.1908 ... 114.3036 114.304  114.3044]
 ...
 [114.19   114.1904 114.1908 ... 114.3036 114.304  114.3044]
 [114.19   114.1904 114.1908 ... 114.3036 114.304  114.3044]
 [114.19   114.1904 114.1908 ... 114.3036 114.304  114.3044]]
Y
[[22.1778 22.1778 22.1778 ... 22.1778 22.1778 22.1778]
 [22.1782 22.1782 22.1782 ... 22.1782 22.1782 22.1782]
 [22.1786 22.1786 22.1786 ... 22.1786 22.1786 22.1786]
 ...
 [22.2606 22.2606 22.2606 ... 22.2606 22.2606 22.2606]
 [22.261  22.261  22.261  ... 22.261  22.261  22.261 ]
 [22.2614 22.2614 22.2614 ... 22.2614 22.2614 22.2614]]
Wave height
[[0.26370001 0.26449999 0.26519999 ... 0.02671    0.0233     0.02034   ]
 [0.27329999 0.2

In [16]:
print(finalNumpyArrayOne.shape)

(210, 287)
